export const endpoints = {
  auth: {
    login: '/auth/login',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
  },
  attendance: {
    checkIn: '/attendance/check-in',
    checkOut: '/attendance/check-out',
    myRecords: '/attendance/my-records',
    records: '/attendance/records',
    adjust: (id: string) => `/attendance/records/${id}`,
  },
  schedules: {
    mine: '/schedules/my-schedule',
    list: '/schedules',
    detail: (id: string) => `/schedules/${id}`,
  },
  leaves: {
    create: '/leaves',
    mine: '/leaves/my-leaves',
    list: '/leaves',
    pending: '/leaves/pending',
    cancel: (id: string) => `/leaves/${id}`,
    approve: (id: string) => `/leaves/${id}/approve`,
    reject: (id: string) => `/leaves/${id}/reject`,
  },
  payroll: {
    mine: '/payroll/my-payroll',
    list: '/payroll',
    detail: (id: string) => `/payroll/${id}`,
    calculate: '/payroll/calculate',
    batch: '/payroll/batch',
    batchHistory: '/payroll/batch-history',
  },
  employees: {
    list: '/employees',
    detail: (id: string) => `/employees/${id}`,
    create: '/employees',
    update: (id: string) => `/employees/${id}`,
    deactivate: (id: string) => `/employees/${id}/deactivate`,
  },
  stores: {
    list: '/stores',
    detail: (id: string) => `/stores/${id}`,
    create: '/stores',
    update: (id: string) => `/stores/${id}`,
    delete: (id: string) => `/stores/${id}`,
  },
  policies: {
    list: '/payroll-policies',
    active: '/payroll-policies/active',
    create: '/payroll-policies',
    update: (id: string) => `/payroll-policies/${id}`,
    delete: (id: string) => `/payroll-policies/${id}`,
  },
} as const
